name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - mika-f
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: add-on-version
    attributes:
      label: Add-on Version
      description: What version of Add-on are you running?
      options:
        - 2.0.0
        - 2.1.0
        - 2.2.0
        - 2.3.0
        - 2.4.0
        - 2.5.0
        - 2.6.0
        - 2.7.0
        - 2.7.1
        - 2.8.0
        - 2.9.0
        - 2.10.0
        - 2.11.0
        - 2.12.0
    validations:
      required: true
  - type: dropdown
    id: blender-version
    attributes:
      label: Blender versions
      description: What version of Blender are you running?
      multiple: true
      options:
        - 3.1.0
        - 3.1.1
        - 3.1.2
        - 3.2.0
        - 3.2.1
        - 3.2.2
        - 3.3.0
        - 3.3.1
        - 3.3.2
        - 3.3.3
        - 3.3.4
        - 3.4.0
        - 3.4.1
        - 3.5.0
        - 3.5.1
        - 3.6.0
        - 3.6.1
        - 3.6.2
        - 3.6.4
        - 3.6.5
        - 4.0.0
        - edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
